config/routes.rb
Rails.application.routes.draw do
  root to: 'recruitments#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :desks
  end
  resources :myteams
  resources :recruitments, only: [:index]
  resources :friends
  resources :parties do
    resources :party_members do
      patch :accept_request
      patch :decline_request
    end
  end
  resources :teams
  resources :scouts
end

app/models/desk.rb
class Desk < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  with_options presence: true do
    validates :image
    validates :desk_text
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :friend_tag_relations, dependent: :destroy
  has_many :friend_tags, through: :friend_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :friend_title
    validates :friend_game_id
    validates :friend_text
  end
end

app/models/friend_tag.rb
class FriendTag < ApplicationRecord
  has_many :friend_tag_relations, dependent: :destroy
  has_many :friends, through: :friend_tag_relations, dependent: :destroy
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '男' },
    { id: 2, name: '女' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/myteam.rb
class Myteam < ApplicationRecord
  belongs_to :user
  has_many :teams

  with_options presence: true do
    validates :team_name
    validates :team_profile
  end
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
  has_many :party_members
  has_many :party_tag_relations, dependent: :destroy
  has_many :party_tags, through: :party_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :party_title
    validates :party_game_id
    validates :party_text
  end

  def new_party
    ApplicationRecord.transaction do
      save!
      PartyMember.create!(user_id: user.id, party_id: id, role: :manager, status: :accept)
      true
    rescue ActiveRecord::RecordInvalid
      false
    end
  end
end

app/models/party_member.rb
class PartyMember < ApplicationRecord
  belongs_to :party
  belongs_to :user

  enum role: { free: 0, manager: 1, member: 2 }
  enum status: { request: 0, accept: 1, decline: 2 }

  def accept_request
    if request?
      ApplicationRecord.transaction do
        accept!
        member!
      end
    end
  end

  def decline_request
    decline! if request?
  end
end

app/models/party_tag.rb
class PartyTag < ApplicationRecord
  has_many :party_tag_relations, dependent: :destroy
  has_many :parties, through: :party_tag_relations, dependent: :destroy
end

app/models/scout.rb
class Scout < ApplicationRecord
  belongs_to :user
  has_many :scout_tag_relations, dependent: :destroy
  has_many :scout_tags, through: :scout_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :scout_title
    validates :scout_game_id
    validates :scout_text
  end
end

app/models/scout_tag.rb
class ScoutTag < ApplicationRecord
  has_many :scout_tag_relations, dependent: :destroy
  has_many :scouts, through: :scout_tag_relations, dependent: :destroy
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :myteam
  has_many :team_tag_relations, dependent: :destroy
  has_many :team_tags, through: :team_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :team_title
    validates :team_game_id
    validates :team_text
  end
end

app/models/team_tag.rb
class TeamTag < ApplicationRecord
  has_many :team_tag_relations, dependent: :destroy
  has_many :teams, through: :team_tag_relations, dependent: :destroy
end

app/models/team_tag_relation.rb
class TeamTagRelation < ApplicationRecord
  belongs_to :team
  belongs_to :team_tag
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_one :desk
  has_many :friends
  has_many :parties
  has_many :scouts
  has_many :myteams
  has_many :teams
  has_many :sns_credentials
  has_many :party_members

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[twitter google_oauth2]

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      nickname: auth.info.nickname,
      email: auth.info.email,
      image: auth.info.image
    )

    # userが登録済みか判定
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :create

  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :update, allow_blank: true

  with_options presence: true do
    validates :nickname, length: { maximum: 25, message: 'must be 1 - 25 characters.' }
  end

  validates :gender_id, inclusion: { in: 1..3, message: 'must be 1 - 3.' }, allow_blank: true

  with_options allow_blank: true, format: { with: /\A[a-zA-Z0-9]/, message: 'must be half-width characters.' } do
    validates :twitter_name, length: { minimum: 4, maximum: 15, message: 'must be 4 - 15 characters.' }
    validates :twitch_name, length: { minimum: 4, maximum: 25, message: 'must be 4 - 25 characters.' }
  end

  validates :mildom_name, numericality: { only_integer: true, message: 'must be half-width numbers.' }, allow_blank: true

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_party, only: %i[show edit update destroy]
  before_action :user_id_check, only: %i[edit destroy]
  before_action :search_party, only: %i[index]

  def index
    # @parties = Party.order('created_at DESC').limit(24)
    @q = Party.ransack(params[:q])
    @parties = @q.result(distinct: true).order('created_at DESC').page(params[:page]).per(12)
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)

    if @party.new_party
      redirect_to parties_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @party.update(party_params)
      redirect_to party_path(@party)
    else
      render :edit
    end
  end

  def destroy
    redirect_to parties_path if @party.destroy
  end

  private

  def user_id_check
    redirect_to root_path unless current_user.id == @party.user_id
  end

  def set_party
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(
      :party_title,
      :party_game_id,
      :party_text,
      party_tag_ids: []
    ).merge(user_id: current_user.id)
  end

  def search_party
    @q = Party.ransack(params[:q]) # 検索オブジェクトを生成
  end

  def party_new; end
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/myteams_helper.rb
module MyteamsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parties/_form.html.erb
<%= form_with model: @party, local: true do |f| %>

  <div class="new-item">

    <%= render 'shared/error_messages', model: @party %>

    <div class="weight-bold-text">
      タイトル
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :party_title, class: "text-input", id: "item-title", placeholder: "募集タイトル", maxlength: "40"%>

    <div class="weight-bold-text">
      ゲームID
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :party_game_id, class: "text-input", id: "item-game-id", placeholder:"GamerID#0000" %>

    <div class="weight-bold-text">
      タグ
      <div class="tag-container">
        <%= f.collection_check_boxes(:party_tag_ids, PartyTag.all, :id, :name) do |tag| %>
          <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="new-item-text">
      <div class="weight-bold-text">
        募集内容
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :party_text, class: "text-input text-box", id: "item-text", placeholder: "募集文", rows: "7", maxlength: "1000" %>
    </div>

    <div class="submit-btn-contents">
      <%= f.submit "掲載する", class: "btn submit-btn" %>
      <%= link_to 'BACK', parties_path, class: "btn back-btn" %>
    </div>
  </div>

<% end %>

app/views/parties/_list.html.erb
  <div class="item-lists">
    <% if user_signed_in? %>
      <% @parties.each do |party| %>
        <%= react_component("PartyList", {post: party, tags: party.party_tags, userId: current_user.id, date: party.updated_at.strftime('%Y/%m/%d %H:%M'), members: User.where(id: PartyMember.where(party_id: party.id).where.not(role: :free).pluck(:user_id)).pluck(:nickname), requested: PartyMember.where(party_id: party.id).where(user_id: current_user.id).exists?}) %>
      <% end %>
    <% else %>
      <% @parties.each do |party| %>
        <%= react_component("PartyList", {post: party, tags: party.party_tags, date: party.updated_at.strftime('%Y/%m/%d %H:%M'), members: User.where(id: PartyMember.where(party_id: party.id).where.not(role: :free).pluck(:user_id)).pluck(:nickname), requested: true}) %>
      <% end %>
    <% end %>
  </div>

app/views/parties/_party.html.erb
<li class="list">
  <%= link_to party_path(party) do %>

    <div class="item-title">
      <h3><%= party.party_title %></h3>
      <span class="category">PARTY</span>
    </div>

  <div class="item-info">
  
    <div class="item-game-id">
      <%= party.party_game_id %>
    </div>

    <div class="item-text">
      <%= party.party_text %>
    </div>

  </div>
  <% end %>
</li>

app/views/parties/edit.html.erb
<%= render 'shared/header' %>

<div class="main-container">
  <div class="new-main">
    <div class="title-wrapper">
      <h1 class="show-title">PARTY</h1>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/parties/index.html.erb
<%= render 'shared/header' %>

<div class="btn-container">
  <%= link_to new_party_path,class: "text-decoration-none" do %>
    <%= render 'shared/new_rec_button' %>
  <% end %>
</div>

<div class="main-container" id="root">
  <h1 class="list-title-text">// PARTY RECRUITMENTS</h1>
  <h1 class="title title-top">PARTY</h1>

  <section class="search-form">
    <%= search_form_for @q, class: "search-section" do |f| %>

    <div class="search-item">

      <%= f.search_field :party_title_cont, placeholder:"TITLE" %>
    </div>

    <div class="search-item">

      <%= f.search_field :party_game_id_cont, placeholder:"NAME" %>
    </div>

    <div class="search-item">

      <%= f.search_field :party_text_cont, placeholder:"BODY" %>
    </div>

    <div class="tag-search-item">


      <div class="">
        <%= f.collection_check_boxes(:party_tags_name_in, PartyTag.all, :name, :name) do |tag| %>
          <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="search-submit-btn-container">
      <%= f.submit "SEARCH", class: "btn submit-btn" %>
    </div>
    <% end %>
  </section>

  <%= paginate @parties %>
  <%= render 'list' %>
  <%= paginate @parties %>

  <ul class="item-lists">
    <%# render partial: 'party', collection: @parties %>
  </ul>
</div>

app/views/parties/new.html.erb
<%= render 'shared/header' %>

<div class="main-container">
  <h1 class="list-title-text">// PARTY RECRUITMENT</h1>
  <div class="new-main">
    <div class="title-wrapper">
      <h1 class="show-title">パーティー募集</h1>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/parties/show.html.erb
<%= render 'shared/header' %>

<div class="btn-container">
  <%= link_to new_party_path do %>
    <div class="new-rec-button">
      <p class="new-rec-button-text">投稿</p>
    </div>
  <% end %>
</div>

<div class="main-container">
  <div class="show-main">
    <h1 class="show-title">PARTY</h1>

    <div class="show-container">
      <div class="show-item">
        <p class="label-text">TITLE:</p>
        <h3><%= @party.party_title %></h3>
      </div>

      <div class="show-item">
        <p class="label-text">NAME:</p>
        <%= link_to @party.party_game_id, user_path(@party.user_id), class: "game-id" %>
      </div>

      <div class="show-item">
        <p class="label-text">TAGS:</p>
        <div class="tag-container">
          <% @party.party_tags.each do |tag| %>
            <span class='tag'><%= tag.name %></span>
          <% end %>
        </div>
      </div>

      <div class="show-item show-about-bg">
        <p class="label-text">DESCRIPTION:</p>
        <%= @party.party_text %>
      </div>
    </div>

  </div>

    <div class="show-buttons">
      <% if current_user == @party.user %>
        <%= link_to 'リクエストリスト', party_party_members_path(@party), class: "btn edit-btn" %>
        <%= link_to '編集', edit_party_path(@party), class: "btn edit-btn" %>
        <%= link_to '削除', party_path(@party), method: :delete, class: "btn delete-btn" %>
      <% end %>
    </div>

</div>