config/routes.rb
Rails.application.routes.draw do
  root to: 'recruitments#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :desks
  end
  resources :myteams
  resources :recruitments, only: [:index]
  resources :friends
  resources :parties do
    resources :party_members do
      patch :accept_request
      patch :decline_request
    end
  end
  resources :teams
  resources :scouts
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_one :desk
  has_many :friends
  has_many :parties
  has_many :scouts
  has_many :myteams
  has_many :teams
  has_many :sns_credentials
  has_many :party_members

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[twitter google_oauth2]

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      nickname: auth.info.nickname,
      email: auth.info.email,
      image: auth.info.image
    )

    # userが登録済みか判定
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :create

  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :update, allow_blank: true

  with_options presence: true do
    validates :nickname, length: { maximum: 25, message: 'must be 1 - 25 characters.' }
  end

  validates :gender_id, inclusion: { in: 1..3, message: 'must be 1 - 3.' }, allow_blank: true

  with_options allow_blank: true, format: { with: /\A[a-zA-Z0-9]/, message: 'must be half-width characters.' } do
    validates :twitter_name, length: { minimum: 4, maximum: 15, message: 'must be 4 - 15 characters.' }
    validates :twitch_name, length: { minimum: 4, maximum: 25, message: 'must be 4 - 25 characters.' }
  end

  validates :mildom_name, numericality: { only_integer: true, message: 'must be half-width numbers.' }, allow_blank: true

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token + 'aA0'
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_user, only: %i[show edit update destroy]

  def show
    @user = User.find(params[:id])
    @desk = Desk.find_by(user_id: @user.id)
    @myteams = Myteam.where(user_id: @user.id).order('created_at DESC')
    @friends = Friend.where(user_id: @user.id).order('created_at DESC')
    @parties = Party.where(user_id: @user.id).order('created_at DESC')
    @teams = Team.where(user_id: @user.id).order('created_at DESC')
    @scouts = Scout.where(user_id: @user.id).order('created_at DESC')
  end

  def edit
    redirect_to root_path unless current_user.id == @user.id
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :nickname,
      :gender_id,
      :birthday,
      :twitter_name,
      :twitch_name,
      :mildom_name,
      :profile
    )
  end

  protected

  def update_resource(_resource, params)
    @user.update_without_password(params)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'shared/header' %>

<div class="main-container">
  <div class="new-main">
    <div class="title-wrapper">
      <h1 class="show-title">PROFILE</h1>
    </div>
    <%= form_with model: @user, local: true do |f| %>

    <div class="new-item">

      <div class="weight-bold-text">
        ニックネーム
      </div>
      <%= f.text_area :nickname, class: "text-input", id: "item-title", placeholder: "Nickname", maxlength: "40"%>

      <div class="weight-bold-text user-select">
        性別 <%= f.collection_select :gender_id, Gender.all, :id, :name, {include_blank: "---"}, {class: ""}%><br>
      </div>

      <div class="weight-bold-text user-select">
      誕生日 <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "年", "月") + "日" %>
      </div>

      <div class="weight-bold-text">
        Twitter
      </div>
      <div class="sns-container">
        <p class="sns-url">twitter.com/</p><%= f.text_area :twitter_name, class: "text-input text-sns", id: "item-title", placeholder: "name", maxlength: "40"%>
      </div>
      
      <div class="weight-bold-text">
        Twitch
      </div>
      <div class="sns-container">
        <p class="sns-url">twitch.tv/</p><%= f.text_area :twitch_name, class: "text-input text-sns", id: "item-title", placeholder: "name", maxlength: "40"%>
      </div>
      
      <div class="weight-bold-text">
        Mildom
      </div>
      <div class="sns-container">
        <p class="sns-url">mildom.com/</p><%= f.text_area :mildom_name, class: "text-input text-sns", id: "item-title", placeholder: "00000000", maxlength: "40"%>
      </div>
      
      <div class="new-item-text">
        <div class="weight-bold-text">
          プロフィール
        </div>
        <%= f.text_area :profile, class: "text-input text-box", id: "item-text", placeholder: "Profile text", rows: "7", maxlength: "1000" %>
      </div>

      <div class="submit-btn-contents">
        <%= f.submit "更新", class: "btn submit-btn" %>
        <%= link_to 'BACK', root_path, class: "btn back-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "shared/header" %>

<div class="main-container">

  <%= form_with model: @user, url: user_registration_path, class: 'registration-main', local: true do |f| %>

    <div class="registration-wrapper">
      <%= render 'shared/error_messages', model: @user %>

      <div class="title-wrapper">
        <h1 class="show-title">SIGN UP</h1>
      </div>

      <div class="form-group">
        <div class='weight-bold-text'>
          ニックネーム
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :nickname, class:"text-input", id:"nickname", placeholder:"ニックネーム", maxlength:"40" %>
      </div>

      <div class="form-group">
        <div class='weight-bold-text'>
          <label class="form-text">メールアドレス</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.email_field :email, class:"text-input", id:"email", placeholder:"sample@email.com" %>
      </div>

      <% if @sns_id.present? %>
        <%= hidden_field_tag :sns_auth, true %>
      <% else %>
        <div class="form-group">
          <div class='weight-bold-text'>
            <label class="form-text">パスワード</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.password_field :password, class:"text-input", id:"password", placeholder:"6文字以上の半角英数字" %>
          <p class="label-text">※英字と数字の両方を含めて設定してください</p>
        </div>

        <div class="form-group">
          <div class='weight-bold-text'>
            <label class="form-text">パスワード(確認)</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.password_field :password_confirmation, class:"text-input", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
        </div>
      <% end %>

      <div class='register-btn-container'>
        <%= f.submit "会員登録" ,class:"btn register-btn" %>
      </div>      
    </div>

  <% end %>

</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<div class="btn-container">

  <% if user_signed_in? %>
    <% if current_user.id == @user.id %>

      <%= link_to new_myteam_path do %>
        <div class="new-rec-button">
          <p class="new-rec-button-text">TEAM</p>
        </div>
      <% end %>

      <% unless Desk.exists?(user_id: @user.id) %>
        <%= link_to new_user_desk_path(@user) do %>
          <div class="new-rec-button">
            <p class="new-rec-button-text">DESK</p>
          </div>
        <% end %>
      <% end %>

    <% end %>
  <% end %>

</div>

<div class="main-container" id="root">
  <h1 class="list-title-text">// <%= @user.nickname %> DETAIL</h1>

  <div class="show-main">
    <h1 class="show-title">PROFILE</h1>

    <div class="show-container">
      <div class="show-item">
        <p class="label-text">NAME:</p>
        <div class="nickname">
          <%= @user.nickname %>
        </div>
      </div>


      <div class="gender-date-group">
      
        <% unless @user.gender_id.blank? %>
          <div class="show-item item-birthday">
            <p class="label-text">GENDER:</p>
            <%= @user.gender.name %>
          </div>
        <% end %>

        <% unless @user.birthday.blank? %>
          <div class="show-item item-birthday">
            <p class="label-text">BIRTHDAY:</p>
            <div class="birthday">
              <%= @user.birthday.strftime('%Y/%m/%d') %>
            </div>
          </div>
        <% end %>

        <div class="show-item item-birthday">
          <p class="label-text">JOIN DATE:</p>
          <div class="joindate">
            <%= @user.created_at.strftime('%Y/%m/%d') %>
          </div>
        </div>

      </div>

      <div class="show-item">

        <% unless @user.twitter_name.blank? && @user.twitch_name.blank? && @user.mildom_name.blank? %>
          <p class="label-text">SNS:</p>
        <% end %>

        <% unless @user.twitter_name.blank? %>
          <div class="twitter">
            <a href="https://twitter.com/<%= @user.twitter_name %>" class="user-sns">
              <i class="fab fa-twitter"></i> <%= @user.twitter_name %>
            </a>
          </div>
        <% end %>

        <% unless @user.twitch_name.blank? %>
          <div class="twitch">
            <a href="https://www.twitch.tv/<%= @user.twitch_name %>" class="user-sns">
              <i class="fab fa-twitch"></i> <%= @user.twitch_name %>
            </a>
          </div>
        <% end %>

        <% unless @user.mildom_name.blank? %>
          <div class="mildom">
            <a href="https://www.mildom.com/<%= @user.mildom_name %>" class="user-sns">
              <i class="fas fa-video"></i> <%= @user.mildom_name %>
            </a>
          </div>
        <% end %>

      </div>

      <div class="show-item">
        <div class="show-about-bg">      
          <p class="label-text">ABOUT ME:</p>
          <div class="profile text-box">
            <%= @user.profile %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <div class="show-buttons">
    <% if current_user == @user %>
      <%= link_to '編集', edit_user_path(@user), class: "btn edit-btn" %>
    <% end %>
  </div>

  <% if Desk.exists?(user_id: @user.id) %>

    <div class="show-main">
      <h1 class="show-title">DESK</h1>

      <div class="show-container">
        <div class="desk-img-container">
          <%= image_tag @desk.image, class: "img-desk" %>
        </div>

        <div class="show-item">
          <div class="show-about-bg">          
            <p class="label-text">ABOUT DESK:</p>
            <div class="profile">
              <%= @desk.desk_text %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="show-buttons">
      <% if current_user == @user %>
        <%= link_to 'デスクを削除', user_desk_path(@user), method: :delete, class: "btn delete-btn" %>
      <% end %>
    </div>

    
  <% end %>

  <% if Myteam.exists?(user_id: @user.id) %>

    <div class="show-main">
      <h1 class="show-title">TEAMS</h1>

      <div class="show-container">
        <ul class="myteam-lists">
          <% @myteams.each do |myteam| %>
            <li class="myteam-list">
              <%= link_to myteam_path(myteam) do %>
                <%= myteam.team_name %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  <% end %>

  <% if @friends.present? || @parties.present? || @teams.present? || @scouts.present? %>

  <div class="show-main user-post-list">
    <h1 class="show-title"><%= @user.nickname %>'s POSTs</h1>
      <%= render 'friends/list' %>
      <%= render 'parties/list' %>
      <%= render 'teams/list' %>
      <%= render 'scouts/list' %>
  </div>

  <% end %>

</div>