config/routes.rb
Rails.application.routes.draw do
  root to: 'recruitments#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :desks
  end
  resources :myteams
  resources :recruitments, only: [:index]
  resources :friends
  resources :parties do
    resources :party_members do
      patch :accept_request
      patch :decline_request
    end
  end
  resources :teams
  resources :scouts
end

app/models/desk.rb
class Desk < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  with_options presence: true do
    validates :image
    validates :desk_text
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :friend_tag_relations, dependent: :destroy
  has_many :friend_tags, through: :friend_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :friend_title
    validates :friend_game_id
    validates :friend_text
  end
end

app/models/friend_tag.rb
class FriendTag < ApplicationRecord
  has_many :friend_tag_relations, dependent: :destroy
  has_many :friends, through: :friend_tag_relations, dependent: :destroy
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '男' },
    { id: 2, name: '女' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/myteam.rb
class Myteam < ApplicationRecord
  belongs_to :user
  has_many :teams

  with_options presence: true do
    validates :team_name
    validates :team_profile
  end
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
  has_many :party_members
  has_many :party_tag_relations, dependent: :destroy
  has_many :party_tags, through: :party_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :party_title
    validates :party_game_id
    validates :party_text
  end

  def new_party
    ApplicationRecord.transaction do
      save!
      PartyMember.create!(user_id: user.id, party_id: id, role: :manager, status: :accept)
      true
    rescue ActiveRecord::RecordInvalid
      false
    end
  end
end

app/models/party_member.rb
class PartyMember < ApplicationRecord
  belongs_to :party
  belongs_to :user

  enum role: { free: 0, manager: 1, member: 2 }
  enum status: { request: 0, accept: 1, decline: 2 }

  def accept_request
    if request?
      ApplicationRecord.transaction do
        accept!
        member!
      end
    end
  end

  def decline_request
    decline! if request?
  end
end

app/models/party_tag.rb
class PartyTag < ApplicationRecord
  has_many :party_tag_relations, dependent: :destroy
  has_many :parties, through: :party_tag_relations, dependent: :destroy
end

app/models/scout.rb
class Scout < ApplicationRecord
  belongs_to :user
  has_many :scout_tag_relations, dependent: :destroy
  has_many :scout_tags, through: :scout_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :scout_title
    validates :scout_game_id
    validates :scout_text
  end
end

app/models/scout_tag.rb
class ScoutTag < ApplicationRecord
  has_many :scout_tag_relations, dependent: :destroy
  has_many :scouts, through: :scout_tag_relations, dependent: :destroy
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :myteam
  has_many :team_tag_relations, dependent: :destroy
  has_many :team_tags, through: :team_tag_relations, dependent: :destroy

  with_options presence: true do
    validates :team_title
    validates :team_game_id
    validates :team_text
  end
end

app/models/team_tag.rb
class TeamTag < ApplicationRecord
  has_many :team_tag_relations, dependent: :destroy
  has_many :teams, through: :team_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender

  has_one :desk
  has_many :friends
  has_many :parties
  has_many :scouts
  has_many :myteams
  has_many :teams
  has_many :sns_credentials
  has_many :party_members

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[twitter google_oauth2]

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      nickname: auth.info.nickname,
      email: auth.info.email,
      image: auth.info.image
    )

    # userが登録済みか判定
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :create

  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Password must includes letter and number.', on: :update, allow_blank: true

  with_options presence: true do
    validates :nickname, length: { maximum: 25, message: 'must be 1 - 25 characters.' }
  end

  validates :gender_id, inclusion: { in: 1..3, message: 'must be 1 - 3.' }, allow_blank: true

  with_options allow_blank: true, format: { with: /\A[a-zA-Z0-9]/, message: 'must be half-width characters.' } do
    validates :twitter_name, length: { minimum: 4, maximum: 15, message: 'must be 4 - 15 characters.' }
    validates :twitch_name, length: { minimum: 4, maximum: 25, message: 'must be 4 - 25 characters.' }
  end

  validates :mildom_name, numericality: { only_integer: true, message: 'must be half-width numbers.' }, allow_blank: true

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/myteams_helper.rb
module MyteamsHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamPlz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <%= link_to root_path do %>
    <div class="logo">

      <%= image_tag 'logo.svg', class: "logo-img" %>

      <div class="logo-text">
        <div class="logo-name">TEAM - PLZ</div>
        <div class="logo-sub-name">For Gamers</div>
      </div>

    </div>
  <% end %>

  <div class='nav'>

    <ul class='lists-left'>
      <li><%= link_to 'FRIEND', friends_path, class: "friend-list" %></li>
      <li><%= link_to 'PARTY', parties_path, class: "party-list" %></li>
      <li><%= link_to 'TEAM', teams_path, class: "team-list" %></li>
      <li><%= link_to 'SCOUT', scouts_path, class: "scout-list" %></li>
    </ul>

    <ul class='lists-right'>
      <%# ログイン状態でheaderの表示を変更 %>
      <% if user_signed_in? %>
        <%= react_component("HeaderUserMenu", {uid: current_user.id, name: current_user.nickname}) %>
      <% else %>
        <li><%= link_to 'LOGIN', new_user_session_path, class: "login" %></li>
        <li><%= link_to 'JOIN NOW', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>

  </div>
</header>

app/views/shared/_new_rec_button.html.erb
<div class="new-rec-button">
  <p class="new-rec-button-text">POST</p>
</div>